export const GET_OPENED_DETAIL = 'GET_OPENED_DETAIL';
export const GET_HISTORY_DATA = 'GET_HISTORY_DATA';
export const GET_HISTORY_DATE = 'GET_HISTORY_DATE';
export const GET_UPCOMING_DATA = 'GET_UPCOMING_DATA';
export const GET_RELATION_DATA = 'GET_RELATION_DATA';
export const GET_RELATION_FILTERED_DATA = 'GET_RELATION_FILTERED_DATA';
export const GET_INPLAY_DATA = 'GET_INPLAY_DATA';
export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';
