export const GET_OPENED_DETAIL = 'GET_OPENED_DETAIL';
export const GET_HISTORY_DATE = 'GET_HISTORY_DATE';
export const GET_RELATION_DATA = 'GET_RELATION_DATA';
export const GET_RELATION_FILTERED_DATA = 'GET_RELATION_FILTERED_DATA';
export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';
export const GET_USER_STATUS = 'GET_USER_STATUS';
